// flow-typed signature: d0b675a9271acaa0b19d7215debae701
// flow-typed version: <<STUB>>/pubsub-js_vvx.x.x/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pubsub-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pubsub-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pubsub-js/iframe/pubsub-bridge' {
  declare module.exports: any;
}

declare module 'pubsub-js/src/pubsub' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/helper' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-bug-9' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-clearSubscriptions' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-hierarchical-addressing' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-issue-54' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-publish' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-subscribe' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-subscribeOnce' {
  declare module.exports: any;
}

declare module 'pubsub-js/test/test-unsubscribe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pubsub-js/iframe/pubsub-bridge.js' {
  declare module.exports: $Exports<'pubsub-js/iframe/pubsub-bridge'>;
}
declare module 'pubsub-js/src/pubsub.js' {
  declare module.exports: $Exports<'pubsub-js/src/pubsub'>;
}
declare module 'pubsub-js/test/helper.js' {
  declare module.exports: $Exports<'pubsub-js/test/helper'>;
}
declare module 'pubsub-js/test/test-bug-9.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-bug-9'>;
}
declare module 'pubsub-js/test/test-clearSubscriptions.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-clearSubscriptions'>;
}
declare module 'pubsub-js/test/test-hierarchical-addressing.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-hierarchical-addressing'>;
}
declare module 'pubsub-js/test/test-issue-54.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-issue-54'>;
}
declare module 'pubsub-js/test/test-publish.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-publish'>;
}
declare module 'pubsub-js/test/test-subscribe.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-subscribe'>;
}
declare module 'pubsub-js/test/test-subscribeOnce.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-subscribeOnce'>;
}
declare module 'pubsub-js/test/test-unsubscribe.js' {
  declare module.exports: $Exports<'pubsub-js/test/test-unsubscribe'>;
}
