// flow-typed signature: 69e39664f64df6ea94bd36c08d015032
// flow-typed version: <<STUB>>/react-broadcast_vv0.6.x/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-broadcast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-broadcast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-broadcast/cjs/react-broadcast' {
  declare module.exports: any;
}

declare module 'react-broadcast/esm/react-broadcast' {
  declare module.exports: any;
}

declare module 'react-broadcast/umd/react-broadcast' {
  declare module.exports: any;
}

declare module 'react-broadcast/umd/react-broadcast.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-broadcast/cjs/react-broadcast.js' {
  declare module.exports: $Exports<'react-broadcast/cjs/react-broadcast'>;
}
declare module 'react-broadcast/esm/react-broadcast.js' {
  declare module.exports: $Exports<'react-broadcast/esm/react-broadcast'>;
}
declare module 'react-broadcast/umd/react-broadcast.js' {
  declare module.exports: $Exports<'react-broadcast/umd/react-broadcast'>;
}
declare module 'react-broadcast/umd/react-broadcast.min.js' {
  declare module.exports: $Exports<'react-broadcast/umd/react-broadcast.min'>;
}
